# Generated by Django 3.0.2 on 2020-02-06 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
